---
# My main YML

# To Enable ssh on all servers
#- hosts: all
#  gather_facts: false
#  become: true
#  become_user: ec2-user
#  tasks:
#  - name: Setup SSH on All Hosts
#    command: 

- hosts: all
  become: true
  gather_facts: false
  tasks: 
  - name: Install Repos
    include_role:
      name: common
    tags:
      - setup_common
    
# To Install HAProxy
- hosts: proxyservers
  gather_facts: false
  become: true
  become_user: ec2-user
  tasks: 
  - name: Setup HAProxy
    include_role: 
      name: haproxy
    tags:
      - install_haproxy

# To Install Tomcat
- hosts: appservers
  gather_facts: false
  become: true
  become_user: ec2-user
  tasks:
  - name: Setup Tomcat
    include_role: 
      name: apache
    tags:
      - install_tomcat
